version: '2'

services:
  mongodb:
    image: bitnami/mongodb:latest
    container_name: mongodb
    privileged: true
    ports:
      - 27017:27017
    volumes:
      - /tmp/mongodb_data:/bitnami/mongodb:rw